PROJECTS = [
    {
        "id": "acme-corp",
        "company": "Acme Corp",
        "subtitle": "Enterprise Deal",
        "status": "negotiation",
        "dealValue": 240000,
        "reps": "4/5",
        "aiInsight": "3 items",
        "activity": "1 call · Feb 16",
        "forecast": 240000,
    },
    {
        "id": "globaltech",
        "company": "GlobalTech",
        "subtitle": "Cloud Migration",
        "status": "demo",
        "dealValue": 0,
        "reps": "3/5",
        "aiInsight": "0 tasks",
        "activity": "4",
        "forecast": 160000,
    },
    {
        "id": "dataflow-labs",
        "company": "DataFlow Labs",
        "subtitle": "Data Infrastructure",
        "status": "proposal",
        "dealValue": 0,
        "reps": "4/5",
        "aiInsight": "1 risk",
        "activity": "1 call · Feb 16",
        "forecast": 120000,
    },
    {
        "id": "novastar-corp",
        "company": "NovaStar Corp",
        "subtitle": "Marketing Suite",
        "status": "closing",
        "dealValue": 0,
        "reps": "3/5",
        "aiInsight": "On track",
        "activity": "4 visits · Feb 20",
        "forecast": 150000,
    },
    {
        "id": "vertex-inc",
        "company": "Vertex Inc.",
        "subtitle": "Security Platform",
        "status": "negotiation",
        "dealValue": 0,
        "reps": "3/5",
        "aiInsight": "2 tasks",
        "activity": "1 call · Jun 10",
        "forecast": 86000,
    },
]

PROJECTS_METRICS = {
    "totalPipeline": "$2.1M",
    "activeDeals": 12,
    "atRisk": 3,
    "forecastEv": "$175K",
}

PROJECT_DETAIL = {
    "id": "acme-corp",
    "company": "Acme Corp Enterprise Deal",
    "dealValue": 240000,
    "status": "Negotiation",
    "recordings": 8,
    "calls": 3,
    "callsSummary": "in this week",
    "meddicScore": 72,
    "meddicTrend": "+8pts",
    "riskLevel": "Medium",
    "riskTrend": "2.1 signals",
    "contacts": [
        {"name": "James Chen", "role": "VP Engineering"},
        {"name": "Lisa Wang", "role": "CTO"},
        {"name": "Annie Liu", "role": "Procurement"},
    ],
    "insights": [
        {
            "icon": "lightbulb",
            "text": 'Current vendor contract ends April 2025 — Creating urgency for this deal',
            "date": "",
        },
        {
            "icon": "alert",
            "text": "Mutual NDA process stalling 15+ touchpoints — 6% key pain point across engineering team",
            "date": "",
        },
        {
            "icon": "check",
            "text": "Board approval requested for deals over $200k — need executive sponsor",
            "date": "",
        },
    ],
    "riskSignals": [
        {
            "icon": "alert-triangle",
            "label": "Budget approval stalling",
            "detail": "No confirmation in 2 follow-ups, originally budget sign-off",
            "status": "warning",
        },
        {
            "icon": "check-circle",
            "label": "Champion key role confirmed",
            "detail": "VP Engineering has been confirming at 1:1 — reiterating support status",
            "status": "resolved",
        },
    ],
}

MEDDIC_DATA = {
    "summary": "The Acme Corp Enterprise deal is at moderate stage. In our latest review, both the Economic Buyer and Decision Criteria are solid, with the key decision-maker (VP Engineering) clearly identified and aligned. The main concern is completing the budgeting cycle and formal sign-off that was expected by Q2 2025.",
    "sections": [
        {
            "key": "metrics",
            "title": "Metrics",
            "icon": "bar-chart",
            "score": 85,
            "content": '$1.2M estimated annual value. Customer estimates the current solution costs approximately $800K annually. Updated revenue estimate is a 3% uplift to YoY, which targets $1.2M in annual business. They are projecting approximately 42% cost reduction over 3 years.',
        },
        {
            "key": "economic_buyer",
            "title": "Economic Buyer",
            "icon": "user",
            "score": 70,
            "content": "James Chen, VP of Engineering, has final purchasing authority for solutions under $500K. For larger deals (over $500K), additional approval from C-Suite is required. He has explicitly confirmed interest in meeting to discuss the Acme Corp proposal.",
        },
        {
            "key": "decision_criteria",
            "title": "Decision Criteria",
            "icon": "list-checks",
            "score": 75,
            "content": "Security compliance is a critical decision factor. The CTO specifically raised SOC 2 Type II certification requirements and asked about data encryption standards. We confirmed two current certifications and are offering to share the full compliance report.",
        },
        {
            "key": "decision_process",
            "title": "Decision Process",
            "icon": "git-branch",
            "score": 60,
            "content": "Formal evaluation includes demos, 1:1 follow-ups, vendor assessment, a trial or pilot run. Final board review at end of Q2. TBD on timing for phase 2 evaluation based on compliance verification with their security team. The go / no-go call will be shared roughly 2 weeks after trial completion.",
        },
        {
            "key": "identify_pain",
            "title": "Identify Pain",
            "icon": "search",
            "score": 80,
            "content": "Customer expressed strong interest in enterprise pricing but has raised concerns about implementation timelines. Key decision maker (VP of Engineering) was present and asked detailed questions about API integration capabilities. The pricing discussion revealed a budget range of $200-300K.",
        },
        {
            "key": "champion",
            "title": "Champion",
            "icon": "trophy",
            "score": 75,
            "content": "VP Engineering James Chen. He is a vocal advocate, reporting directly to C-Suite on engineering evaluations and has confirmed purchase authority. In a close relationship with Lisa (CTO) and the broader technical team. Has shared internal evaluation criteria and timeline proactively.",
        },
    ],
}

TODO_ITEMS = [
    {
        "id": "todo-1",
        "title": "Schedule technical deep-dive with engineering team",
        "fromRecording": "Rec 4",
        "dueDate": "Due: Mar 26",
        "tags": [
            {"label": "Urgent", "color": "red"},
            {"label": "Meeting", "color": "blue"},
        ],
        "action": "Schedule",
        "completed": False,
    },
    {
        "id": "todo-2",
        "title": "Send updated pricing proposal to procurement",
        "fromRecording": "Rec #5",
        "dueDate": "Due: Feb 28",
        "tags": [
            {"label": "High", "color": "orange"},
            {"label": "Urgently", "color": "orange"},
        ],
        "linkedItems": "1 other",
        "action": "Follow Up",
        "completed": False,
    },
    {
        "id": "todo-3",
        "title": "Confirm budget timeline with CFO",
        "fromRecording": "Rec #3",
        "dueDate": "Sat, Mar 1",
        "tags": [{"label": "MEDDIC", "color": "green"}],
        "linkedItems": "1 lead",
        "action": "Follow Up",
        "completed": False,
    },
    {
        "id": "todo-4",
        "title": "Prepare ROI presentation for board meeting",
        "fromRecording": "Rec #6",
        "dueDate": "Due: Dec 15",
        "tags": [{"label": "Critical", "color": "red"}],
        "action": "Follow Up",
        "completed": False,
    },
    {
        "id": "todo-5",
        "title": "Follow up on security audit results",
        "fromRecording": "Rec #2",
        "dueDate": "",
        "tags": [{"label": "High", "color": "orange"}],
        "linkedItems": "1 risk",
        "action": "Follow Up",
        "completed": False,
    },
    {
        "id": "todo-6",
        "title": "Survey after-study to ...",
        "fromRecording": "Rec #1",
        "dueDate": "Complete: Feb 01",
        "tags": [],
        "action": "",
        "completed": True,
    },
]

PROJECT_RECORDINGS = [
    {
        "id": "rec-1",
        "title": "Pricing Review Call",
        "subtitle": "with Engineering",
        "date": "Feb 18, 2025 04 hrs · 85",
        "duration": "44 min",
        "score": 85,
        "participants": 4,
    },
    {
        "id": "rec-2",
        "title": "Technical Demo",
        "subtitle": "with Lisa Wang's team to lead",
        "date": "Feb 12, 2025 08 hrs · 85",
        "duration": "32 min",
        "score": 78,
        "participants": 5,
    },
    {
        "id": "rec-3",
        "title": "Discovery Call",
        "subtitle": "with James Chen + CTO",
        "date": "Feb 5, 2025 05 hrs · 72",
        "duration": "28 min",
        "score": 72,
        "participants": 3,
    },
]

PROJECT_SETTINGS = {
    "connectedApps": [
        {"name": "Gmail", "description": "Sync email notifications", "icon": "mail", "connected": True},
        {"name": "Google Calendar", "description": "Coordinate meetings with your dev...", "icon": "calendar", "connected": True},
        {"name": "Salesforce", "description": "Sync your CRM and pipeline data", "icon": "database", "connected": False},
        {"name": "Slack", "description": "Get notifications on key updates", "icon": "message-square", "connected": True},
    ],
    "aiSkills": [
        {"name": "Call Analysis", "description": "Analyze tone, key points, and action items", "icon": "phone", "enabled": True},
        {"name": "MEDDIC Assessment", "description": "Auto-generate MEDDIC assessments for...", "icon": "clipboard", "enabled": True},
        {"name": "Risk Detection", "description": "Detect deal risk and competitive threats", "icon": "alert-triangle", "enabled": True},
        {"name": "Email Draft Generation", "description": "AI-powered follow-up email drafts based ...", "icon": "mail", "enabled": True},
    ],
    "metrics": [
        {"label": "TOTAL REVENUE", "value": "$48,234", "trend": "+$12.5%"},
        {"label": "TOTAL REVENUE", "value": "$48,234", "trend": "+$12.5%"},
        {"label": "TOTAL REVENUE", "value": "$48,234", "trend": "+$12.5%"},
        {"label": "TOTAL REVENUE", "value": "$48,234", "trend": "+$12.5%"},
    ],
}
