CALL_ANALYSIS = {
    "id": "rec-1",
    "title": "Pricing Review Call",
    "date": "Feb 3, 2025",
    "duration": "44 min",
    "participants": 4,
    "talkRatio": {"rep": 40, "customer": 60},
    "keyTopics": [
        {"label": "Pricing", "percentage": 67},
        {"label": "Timeline", "percentage": None},
        {"label": "Integration", "percentage": None},
        {"label": "Budgeting", "percentage": None},
        {"label": "Directly by", "percentage": None},
    ],
    "analysis": "The customer expressed strong interest in the enterprise pricing tier but raised concerns about the implementation timelines. Key decision maker (VP of Engineering) was present and asked detailed questions about API integration capabilities. The pricing discussion revealed a budget range of $250-300% — slightly below our initial quote of $350K.",
    "callScore": 78,
    "metrics": [
        {"label": "Discovery", "value": "89%", "score": 89},
        {"label": "Value Proposition", "value": "86%", "score": 86},
        {"label": "Objection Handling", "value": "AAA", "score": 65},
        {"label": "Engagement", "value": "90%", "score": 90},
        {"label": "Closing Signals", "value": "", "score": 65},
        {"label": "Follow-up Quality", "value": "", "score": 75},
    ],
    "riskSignals": [
        "Budget Limit — Customer budget ($200-$250K) is below our initial quote ($350K). A phased approach may mitigate this.",
        "Competitive Activity — Customer evaluating two other vendors. Need to differentiate on integration depth and compliance.",
        "Timeline Pressure — Legal review may delay the Q2 close target. Need to proactively engage procurement.",
    ],
    "keyDiscussionPoints": [
        {"text": "Enterprise pricing structure best-fit options", "tag": "Pricing"},
        {"text": "API integration with Salesforce, HQ, and 20+ tools", "tag": "Technical"},
        {"text": "SOC 2 Type II compliance and data security standards", "tag": "Compliance"},
        {"text": "Implementation timeline and phased rollout approach", "tag": "Timeline"},
    ],
    "transcript": [
        {"speaker": "John Dialed", "time": "0:14", "text": "I'd like to walk through our enterprise pricing structure. Based on your team size of 200, you'd fall into our premium tier offering."},
        {"speaker": "Sarah (VP)", "time": "1:30", "text": "Our budget range is between $250K and $350K. Can you tell me more about the 1:1 integration capabilities?"},
        {"speaker": "James Chen", "time": "5:10", "text": "We offer native integrations with Salesforce, Jira, Writ 30+ tools. Let me share our API documentation for your team to review. Recommended to prioritize the Salesforce integration."},
        {"speaker": "Mike (CTO)", "time": "8:30", "text": "What about security compliance? We need SOC 2 Type II certification. Have you established that to date? Is it available in this time?"},
    ],
}
