TEMPLATES = [
    {
        "id": "sales-deal",
        "name": "Sales Deal",
        "description": "Track deal progress with MEDDIC scoring, risk detection, and CRM sync. Ideal for B2B enterprise sales.",
        "icon": "briefcase",
        "badge": "Recommended",
        "comingSoon": False,
        "skills": [
            {"name": "Call Analysis", "description": "Analyze tone, key points, and action items", "icon": "phone", "enabled": True},
            {"name": "MEDDIC Assessment", "description": "Auto-generate MEDDIC assessments from call recordings", "icon": "clipboard", "enabled": True},
            {"name": "Risk Detection", "description": "Detect deal risk and competitive threats", "icon": "alert-triangle", "enabled": True},
            {"name": "Email Draft Generation", "description": "AI-powered follow-up email drafts based on call context", "icon": "mail", "enabled": True},
        ],
        "apps": [
            {"name": "Gmail", "description": "Sync email notifications", "icon": "mail", "connected": True},
            {"name": "Google Calendar", "description": "Coordinate meetings", "icon": "calendar", "connected": True},
            {"name": "Salesforce", "description": "Sync CRM and pipeline data", "icon": "database", "connected": False},
            {"name": "Slack", "description": "Get notifications on key updates", "icon": "message-square", "connected": True},
        ],
    },
    {
        "id": "customer-success",
        "name": "Customer Success",
        "description": "Track customer health, renewal risks, and engagement metrics. Coming soon.",
        "icon": "headphones",
        "comingSoon": True,
        "skills": [],
        "apps": [],
    },
    {
        "id": "hr-interview",
        "name": "HR Interview",
        "description": "Streamline interview feedback, candidate scoring, and hiring workflows. Coming soon.",
        "icon": "users",
        "comingSoon": True,
        "skills": [],
        "apps": [],
    },
]
